spring:
  data:
    mongodb:
      host: 'mongo.spassu.cloud'
      port: '27017'
      username: 'root'
      password: '123456'
      database: 'acelerador'

mongock:
  change-logs-scan-package: 'br.com.spassu.samplemongodb.config.dbmigrations'